# Generated by Django 6.0.4 on 2026-05-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_cancelled",
            field=models.BooleanField(default=False, verbose_name="Отменена"),
        ),
    ]
